### ISSUE TITLE
Should the Dockerhub build be automated?

### ISSUE THREAD

**Issue by jabagawee** [requests/httpbin#383]
I submitted PR #382 (thanks by the way!) to update the Dockerfile for httpbin, but I realized that [the Dockerhub build](http://dockerhub.com/r/kennethreitz/httpbin) was last pushed months ago and is not automatically picking up changes in GitHub.

Would it be desirable to set up a [service hook](https://docs.docker.com/docker-hub/github/#github-service-hooks) in this repo to send automated build requests whenever a push happens? You probably have private repos for yourself and organizations you belong to, so you'd have to manually set up the service hooks. I understand if this is not worth the effort. Thank you.

**Comment by kennethreitz** [comment]
Yeah i don't even remember how to push the image

**Comment by kennethreitz** [comment]
automation would be great

**Comment by kennethreitz** [comment]
if i remember correctly, though, you have to set that up on dockerhub when you create the image

**Comment by jabagawee** [comment]
It might be worth it to delete the repo and start over, unless you have
webhooks on that image that are a pain to recreate or you want to keep your
downloads/stars stats.

Andrew Szeto

**Comment by kennethreitz** [comment]
Will look into it.

**Comment by javabrett** [comment]
With the move of the project to the `requests` org, this might be worth another look, since the integration could be setup for https://hub.docker.com/r/requests/ (doesn't exist yet) replacing https://hub.docker.com/r/kennethreitz/ .  I don't know if there's a migration-path.

The relevant doc is https://docs.docker.com/docker-hub/builds/ .  Note that there are two requirements - one at account setup/integration-setup time, the other for the repo:

> To use automated builds, you must have an account on Docker Hub and on the hosted repository provider (GitHub or Bitbucket). If you have previously linked your Github or Bitbucket account, you must have chosen the Public and Private connection type.

> Select Create > Create Automated Build (from the drop down, upper right) on Docker Hub.

**Comment by kennethreitz** [comment]
:+1:

**Comment by kennethreitz** [comment]
'requests' seems to be taken

**Comment by javabrett** [comment]
I think this is in good shape now and can be closed.  https://hub.docker.com/r/kennethreitz/httpbin/ is now public/automated and building with each master push.

**Comment by mostafazh** [comment]
I agree, I think this can be closed. @javabrett
