### ISSUE TITLE
Make httpbin OS independent again

### ISSUE THREAD

**Issue by 5j9** [requests/httpbin#394]
See https://github.com/kennethreitz/flask-common/issues/4 .
Currently it is not possible to install `httpbin` on Windows machines. If fails with the following error:
```
$ pip install httpbin
Collecting httpbin
  Downloading httpbin-0.6.2-py2.py3-none-any.whl (87kB)
    100% |████████████████████████████████| 92kB 163kB/s
Collecting brotlipy (from httpbin)
  Using cached brotlipy-0.7.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: decorator in c:\users\a\appdata\local\programs\python\python36\lib\site-packages (from httpbin)
Collecting flask-limiter (from httpbin)
  Using cached Flask-Limiter-0.9.5.1.tar.gz
Collecting Flask-Common (from httpbin)
  Using cached Flask-Common-0.2.0.tar.gz
Requirement already satisfied: itsdangerous in c:\users\a\appdata\local\programs\python\python36\lib\site-packages (from httpbin)
Requirement already satisfied: Flask in c:\users\a\appdata\local\programs\python\python36\lib\site-packages (from httpbin)
Requirement already satisfied: six in c:\users\a\appdata\local\programs\python\python36\lib\site-packages (from httpbin)
Collecting raven[flask] (from httpbin)
  Downloading raven-6.2.1-py2.py3-none-any.whl (285kB)
    100% |████████████████████████████████| 286kB 427kB/s
Requirement already satisfied: MarkupSafe in c:\users\a\appdata\local\programs\python\python36\lib\site-packages (from httpbin)
Collecting cffi>=1.0.0 (from brotlipy->httpbin)
  Downloading cffi-1.11.2-cp36-cp36m-win_amd64.whl (166kB)
    100% |████████████████████████████████| 174kB 846kB/s
Collecting limits (from flask-limiter->httpbin)
  Using cached limits-1.2.1.tar.gz
Collecting Gunicorn (from Flask-Common->httpbin)
  Using cached gunicorn-19.7.1-py2.py3-none-any.whl
Collecting WhiteNoise (from Flask-Common->httpbin)
  Downloading whitenoise-3.3.1-py2.py3-none-any.whl
Collecting crayons (from Flask-Common->httpbin)
  Using cached crayons-0.1.2.tar.gz
Collecting maya (from Flask-Common->httpbin)
  Downloading maya-0.3.3-py2.py3-none-any.whl
Collecting flask_cache (from Flask-Common->httpbin)
  Using cached Flask-Cache-0.13.1.tar.gz
Collecting meinheld (from Flask-Common->httpbin)
  Using cached meinheld-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Are you really running a posix compliant OS ?
    Be posix compliant is mandatory

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\a\AppData\Local\Temp\pip-build-prc752k3\meinheld\
```

httpbin 0.5.0 didn't have this issue.
Thanks!

**Comment by sigmavirus24** [comment]
This was Kenneth's decision and work, so I'm assigning it to him to decide what to do.

**Comment by kennethreitz** [comment]
Posix compliance is a fine requirement, for now.

**Comment by kennethreitz** [comment]
We can work to make flask-common optional though — and not a requirement for windows machines.

**Comment by kennethreitz** [comment]
https://docs.pipenv.org/advanced.html#specifying-basically-anything

**Comment by kennethreitz** [comment]
anyone want to take a shot at it?

**Comment by kevin1024** [comment]
I would like to make flask-common optional for another reason:  It does not support python 2.6.  I am using the httpbin package to test other packages that have python 2.6 support, so I would like httpbin to support it as well.

**Comment by sigmavirus24** [comment]
@kevin1024 I respect the desire to support old and EOL'd versions of Python. I do this myself, but it's not fair to push that onto other projects. There are versions of httpbin that support 2.6. You can declare a cap that's dependent upon the `python_version`.

Making things OS independent is a separate task though.

**Comment by kevin1024** [comment]
@sigmavirus24 fair enough, was mostly thinking about requests.  They will need to pin httpbin to make sure their test suite passes so they will miss out on new httpbin features and bugfixes.

**Comment by ldemailly** [comment]
if it's ok to do such a blatant plug, you could give fortio a go, it's in go (ah!) so should work fine on windows : https://github.com/istio/fortio - it doesn't have nearly all the features httpbin does but it has what I found useful so far and I'm happy to add more (or take PRs)

{if it's not ok feel free to delete - my apologies}

**Comment by sigmavirus24** [comment]
@ldemailly that does not actually contribute to the discussion as to how to make httpbin work on windows.

**Comment by 5j9** [comment]
With #447 being merged `httpbin` can be installed on Windows once again.

**Comment by javabrett** [comment]
@5j9 feel free to close this issue if all resolved.
