### ISSUE TITLE
/deflate adds zlib-specific wrapper

### ISSUE THREAD

**Issue by tmenier** [requests/httpbin#419]
I'm not sure if this should be "corrected" or if it's best left as an FYI, but the .NET world [struggles mightily](http://george.chiramattel.com/blog/2007/09/deflatestream-block-length-does-not-match.html) with DEFLATE content that includes [header and trailer bits included by zlib](https://en.wikipedia.org/wiki/Zlib#Encapsulation). As a simple example, this will fail:

```c#
var cli = new HttpClient(new HttpClientHandler {
    AutomaticDecompression = DecompressionMethods.Deflate
});
await cli.GetAsync("https://httpbin.org/deflate");
```

Error:

```
System.IO.InvalidDataException : Block length does not match with its complement.
```

By comparison, the StackExchange API also supports DEFLATE, only without the wrapper, and this works fine:

```c#
var cli = new HttpClient(new HttpClientHandler {
    AutomaticDecompression = DecompressionMethods.Deflate
});
// pass request header, otherwise it defaults to GZIP
cli.DefaultRequestHeaders.TryAddWithoutValidation("Accept-Encoding", "deflate");
await cli.GetAsync("https://api.stackexchange.com/2.2/answers?site=stackoverflow&pagesize=10");
```

I'm not a Python guru, but it does look like `zlib.compressobj` [supports](https://docs.python.org/3/library/zlib.html#zlib.compressobj) outputting the raw content without the wrapper via the optional `wbits` arg. I believe you'd just pass -15 (to override the default 15) [here](https://github.com/kennethreitz/httpbin/blob/master/httpbin/filters.py#L81).

**Comment by javabrett** [comment]
@tmenier thanks for documenting this.  It does seem like an "FYI" and hopefully others will benefit.

The reading I have done, including your links, leads me to understand that:

1. _.NET_ has a `DeflateStream`, which is good for reading the [RFC1951 DEFLATE](https://www.ietf.org/rfc/rfc1951.txt) compression-format.
1. Somewhat confusingly the HTTP specification for [Content-Encoding: deflate](https://tools.ietf.org/html/rfc7230#section-4.2.2), requires `zlib` encoding, which is DEFLATE plus some wrapping header bytes.
1. _.NET_ lacks a core library for `ZLibStream` but there are third-party implementations in common-use.
1. The combination of all the above leads to `DeflateStream` being often used to decode `deflate` encoding (actually `zlib`), leading to an error unless leading bytes header is stripped.

For _httpbin_ I see:

```
curl -vvv http://httpbin.org/deflate
...
< Content-Encoding: deflate
```

... and in the payload the first bytes are `78 9c`, followed by DEFLATE data, which appears to be valid `zlib`.

Does that all look right?  If so I think this issue can be closed as an FYI.

**Comment by tmenier** [comment]
That works for me, thanks.
