### ISSUE TITLE
Don't redirect http to https

### ISSUE THREAD

**Issue by eserte** [requests/httpbin#440]
Currently httpbin does not work as "documented". For example, one of the examples does not return 418 anymore, but 301:
```
$ curl -I http://httpbin.org/status/418
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Sat, 28 Apr 2018 10:04:32 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://httpbin.org:443/status/418
```

This is breaking the test suite of https://github.com/libwww-perl/Net-HTTP (@oalders FYI).

**Comment by kennethreitz** [comment]
The service is now https only.

**Comment by kennethreitz** [comment]
a test suite should be running httpbin locally, not using httpbin's production service.

**Comment by sigmavirus24** [comment]
There are also docker containers if that makes your life simpler for running it locally.

**Comment by kennethreitz** [comment]
Should be back to normal now.

**Comment by oalders** [comment]
Thanks @kennethreitz and @eserte.  I guess we should rethink how we're testing this in `Net::HTTP`.  Getting the tests working again in the meantime is very helpful, though.  We can close this issue now.

**Comment by cup** [comment]
https://github.com/postmanlabs/httpbin/issues/440
https://github.com/postmanlabs/httpbin/issues/489
https://github.com/postmanlabs/httpbin/issues/533
https://github.com/postmanlabs/httpbin/issues/536
https://github.com/postmanlabs/httpbin/issues/545

**Comment by ghost** [comment]
As an alternative this site offers both protocols:

- http://postman-echo.com/get
- https://postman-echo.com/get
