### ISSUE TITLE
httpbin.org unhealthy today

### ISSUE THREAD

**Issue by msabramo** [requests/httpbin#450]
httpbin.org seems to be under the weather today -- getting lots of errors

<img width="1324" alt="screen shot 2018-05-08 at 6 34 31 pm" src="https://user-images.githubusercontent.com/305268/39791110-978fe68a-52ee-11e8-9352-d8d1798ca2bf.png">

**Comment by for-mao** [comment]
when I access 'httpbin.org', I met the same problem.

**Comment by DrickJiang** [comment]
Me too . This website doesn't work now from this morning 10 hours ago.

**Comment by kennethreitz** [comment]
Staging is up. Not sure what the difference is. Debugging.

**Comment by kennethreitz** [comment]
Maintenance mode on. First time I've needed to do that.

**Comment by kennethreitz** [comment]
This is either a DDoS attack, or someone is heavily abusing the service all of a sudden. over 2500r/s.

**Comment by kennethreitz** [comment]
Switching to gevent.

**Comment by kennethreitz** [comment]
gevent seems to be handling the load fine.

**Comment by kennethreitz** [comment]
yay gevent!

**Comment by kennethreitz** [comment]
Also running 24 workers per node now (4 nodes in total).

**Comment by kennethreitz** [comment]
Instead of the default of 8.

**Comment by kennethreitz** [comment]
Runing 6 nodes now.

**Comment by kennethreitz** [comment]
I would enable autoscaling, but this service's unreasonable response times make that problematic.

**Comment by kennethreitz** [comment]
6 nodes seems to keep the incoming http queue much happier.

**Comment by kennethreitz** [comment]
Switched to 2X dynos, as we aren't using the available memory anymore, since we're using gevent, which spawns a single worker.

**Comment by kennethreitz** [comment]
Running 24X of them (same bill rate).

**Comment by kennethreitz** [comment]
Should be over-provisioned.

**Comment by kennethreitz** [comment]
wicked fast now.

**Comment by kennethreitz** [comment]
Scaling down to 18.

**Comment by kennethreitz** [comment]
Now on 24x 1X dynos.

**Comment by simonhampel** [comment]
Working well for me now - thanks.
