### ISSUE TITLE
/headers does not show Via header

### ISSUE THREAD

**Issue by filex** [requests/httpbin#454]
```
curl -s -H x-via:bar -H via:foo 'https://httpbin.org/headers' | jq .
{
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.54.0",
    "X-Via": "bar"
  }
}
```

The `via` header does not show up in the result, while `x-via` does. I would expect both header to be reflected.

**Comment by sigmavirus24** [comment]
Can you try this with a locally running version of httpbin? This is almost certainly due to the fact that we host HTTPbin on Heroku and that has a proxy which strips and/or replaces certain headers.

**Comment by filex** [comment]
I have used the docker image:
```
$ docker run -p 1234:80 kennethreitz/httpbin
[2018-05-18 11:44:26 +0000] [1] [INFO] Starting gunicorn 19.8.1
[2018-05-18 11:44:26 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2018-05-18 11:44:26 +0000] [1] [INFO] Using worker: gevent
[2018-05-18 11:44:26 +0000] [8] [INFO] Booting worker with pid: 8

…
```

But the `via` header still does not appear:

```
$ curl -s -H x-via:bar -H via:foo 'http://localhost:1234/headers' | jq .
{
  "headers": {
    "Accept": "*/*",
    "Host": "localhost:1234",
    "User-Agent": "curl/7.54.0",
    "X-Via": "bar"
  }
}
```

**Comment by sigmavirus24** [comment]
Thanks for confirming.

**Comment by sigmavirus24** [comment]
So we have a list of [`ENV_HEADERS`](https://github.com/requests/httpbin/blob/63a649f753e625feac9196115a8ba74fd36864fe/httpbin/helpers.py#L55) with which we strip things out like `Via`. We need to switch to using [`get_headers`](https://github.com/requests/httpbin/blob/63a649f753e625feac9196115a8ba74fd36864fe/httpbin/helpers.py#L128) in our [view function](https://github.com/requests/httpbin/blob/63a649f753e625feac9196115a8ba74fd36864fe/httpbin/core.py#L232) with a query parameter to toggle the behaviour of hiding the environment or not.

I'd be happy to merge a pull request that does that.

**Comment by sanketsaurav** [comment]
@sigmavirus24 Fixed it in #457. Please let me know if anything else is needed.

**Comment by filex** [comment]
I didn't new about the `show_env` param. Apparently it is already working for `/headers` in `master` (and online):

```
curl -s -H x-via:bar -H via:foo 'https://httpbin.org/headers?show_env' | jq .
{
  "headers": {
    "Accept": "*/*",
    "Connect-Time": "1",
    "Connection": "close",
    "Host": "httpbin.org",
    "Total-Route-Time": "0",
    "User-Agent": "curl/7.54.0",
    "Via": "foo, 1.1 vegur",
    "X-Forwarded-For": "78.34.241.215",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https",
    "X-Request-Id": "24a06c7f-10ff-4b10-9984-b5c1e17203cc",
    "X-Request-Start": "1526745534478",
    "X-Via": "bar"
  }
}
```

**Comment by CapoD** [comment]
@sanketsaurav What is the reason that these headers are not shown by default, since this would make the usage of the swagger UI much more intuitive?

(I used httpbin to examine the headers set by my load balancer and needed a serious amount of time to figure out that the load balancer is working properly and httpbin is just not showing the `X-FORWARDED-FOR` header)

**Comment by sohamsengupta17** [comment]
Also, it seems that the value of X-Forwarded-Proto comes as "http" always, irrespective of the value passed.

**Comment by sohamsengupta17** [comment]
Also note that the values of X-Forwarded-Proto and X-Forwarded-Port in the request are overridden according to whether it's an http or https call that is made.
