### ISSUE TITLE
how about add favicon.ico ? 

### ISSUE THREAD

**Issue by isayme** [requests/httpbin#459]

**Comment by javabrett** [comment]
Do you mean like http://httpbin.org/favicon.ico ?  Any image you have in-mind?

**Comment by isayme** [comment]
@javabrett yes. 
I'm not a designer, maybe someone else could help to get one~~

**Comment by javabrett** [comment]
https://favicon.io/?text=%3A%2F%2F%3F&shape=circle&fontFamily=Marck+Script&fontSize=64&fontColor=%23ff00bc&backgroundColor=%23000000

**Comment by isayme** [comment]
cool~

**Comment by rochacbruno** [comment]
Create a new httpbin/static folder and put the icons there then change it here: https://github.com/requests/httpbin/blob/master/httpbin/templates/flasgger/index.html#L8
