### ISSUE TITLE
500 error on POST to https://httpbin.org/redirect-to 

### ISSUE THREAD

**Issue by eturk1** [requests/httpbin#476]
Is it me or is this failing?

This simple html to POST fails with 500:

```
<h2>POST Redirect test</h2>

<form method="post" action="https://httpbin.org/redirect-to">
	status_code: <input name="status_code" value="302"/>
	url: <input name="url" value="https://www.dartlang.org/"/>
	<button type="submit" >Test</button> 
</form>
```

But GET works great:
```
<h2>GET Redirect test</h2>

<form method="get" action="https://httpbin.org/redirect-to">
	status_code: <input name="status_code" value="302"/>
	url: <input name="url" value="https://www.dartlang.org/"/>
	<button type="submit" >Test</button> 
</form>
```

BTW, all the interactive tests (get, post, etc) fail for me at: https://httpbin.org/#/Redirects/get_redirect_to

**Comment by eturk1** [comment]
@javabrett How about the external POST to https://httpbin.org/redirect-to?

**Comment by javabrett** [comment]
@eturk1 no the first commit did not, but I've added a second which splits-out processing of `POST`, `PUT` and `PATCH`.  I could not get the parameters to render for `PATCH` in Swagger UI 2, but the request is processed correctly.  This required a second logic path to fetch the params from `formData`.  Note that only normal forms are supported, not JSON bodies etc.
