### ISSUE TITLE
The deployment is currently unavailable

### ISSUE THREAD

**Issue by it-can** [requests/httpbin#483]
I constantly get this error when using httpbin.org...

```
curl -X GET "https://httpbin.org/get" -H "accept: application/json"
{"status":"503","description":"The deployment is currently unavailable"}
```

**Comment by 1271** [comment]
You can use this as an alternative: https://httpbin-org.herokuapp.com

(I'm not an author, but it works)

**Comment by javabrett** [comment]
And it looks like it is back up now.
