### ISSUE TITLE
Periodic 503s

### ISSUE THREAD

**Issue by edaniels** [requests/httpbin#486]
Hi! We've been using `httpbin.org` which has been great for testing our SDKs. The only issue we see periodically is that we get 503 status codes back on the `/delete` resource. Do you know why this occurs?

**Comment by andreineculau** [comment]
Same here. I see very very often a 503 response

```
< HTTP/1.1 503 Service Temporarily Unavailable
< Date: Mon, 09 Jul 2018 20:48:45 GMT
< Content-Type: text/plain
< Content-Length: 40
< Connection: keep-alive
< ETag: "5b42e707-28"
< Vary: Accept
< x-now-trace: bru1
< server: now
< now: 1
< cache-control: s-maxage=0
<
The deployment is currently unavailable
```

**Comment by steffenschroeder** [comment]
blindly guessing: might be related to NOW: https://twitter.com/zeithq/status/906643922755211265

**Comment by smileart** [comment]
@edaniels this is the exact reason why I decided to have a local Docker `httpbin` version as a fallback for the tests in my projects. Alas, currently it doesn't work, but there's an issue being tackled right now, so hopefully this option will be available soon: https://github.com/requests/httpbin/issues/484. Maybe you should consider doing the same.

**Comment by andreineculau** [comment]
@smileart regardless of how we use httpbin, it means the service, httpbin.org, is currently not trustworthy. That is primarily what I'm interested in having addressed. If i was throttled, then we would fall in another category of discussions - use docker, pay for unthrottled service, etc

**Comment by edaniels** [comment]
I agree with @andreineculau. I'm willing to pay $X to get a certain amount of guaranteed requests per month such that this can be hosted on an always-on infrastructure.

**Comment by javabrett** [comment]
OK I've seen one of these now.  Whatever NOW does and whatever cadence it does it as, assuming that is what is causing the outages, is different from a previous deployment mechanism.

**Comment by smileart** [comment]
@andreineculau, @edaniels yeah, sure, I totally agree that the issue should be addressed, but there's no such thing as 100% uptime or "always-on infrastructure" per se, so it wouldn't harm to have a backup plan as well as an easy way to switch to it anytime, JIC. 🤷‍♂️ 

Personally I'm waiting for both issues to be addressed since I use it quite often and also would like to have an option to run it locally in a container, but if there was some monetisation option for the project, as [ngrok](https://ngrok.com) has, for example, I wouldn't mind either.

**Comment by kennethreitz** [comment]
we aren't hosted on now.

**Comment by kennethreitz** [comment]
DNS mis-configuration

**Comment by kennethreitz** [comment]
there were two alias records

**Comment by javabrett** [comment]
Based on my observations, I'd say this is fixed/closeable - anyone else seen a recent outage?
