### ISSUE TITLE
Different results for /headers between docker and httpbin.org

### ISSUE THREAD

**Issue by Fishbowler** [requests/httpbin#487]
I'm getting different results for the same request (tested by modify /etc/hosts).

Docker returns:

```
{
	"Abc": "def",
	"Connection": "close",
	"Content-Type": "application/x-www-form-urlencoded",
	"Foo": "bar",
	"Host": "httpbin.org"
}
```

The httpbin.org site returns:

```
{
	"headers": {
		"Abc": "def",
		"Connection": "close",
		"Content-Type": "application/x-www-form-urlencoded",
		"Foo": "bar",
		"Host": "httpbin.org"
	}
}
```

That headers wrapper object being inconsistently present is causing some havoc for tests in our project, where developers use the live site, but CI is using Docker.

**Comment by Fishbowler** [comment]
Current latest - SHA 4d32e6a00db644e3d70a735a21f33d9e5961287fa0e9ff8dd590f270317e2ec2

**Comment by javabrett** [comment]
The behaviour changes in 31ffe79981a079d6605352d2d84de2f2d27ab6db :

```
commit 31ffe79981a079d6605352d2d84de2f2d27ab6db
Author: Sanket Saurav <sanketsaurav@gmail.com>
Date:   Sat May 19 20:37:05 2018 +0530

    Support `show_env` param in `/headers`
    
    If `show_env` is True, then return all the headers without stripping `ENV_HEADERS`. This fixes #454.
    
    Signed-off-by: Sanket Saurav <sanketsaurav@gmail.com>
```

This looks like a regression - I don't expect that the `headers` dict was intentionally removed?

I'd suggest trying to build your docker image on something closer to what is released and deployed to http://httpbin.org .  There's some [Git tags missing](https://github.com/requests/httpbin/issues/488) so best guess at current-GA-deployed/`0.9.0` might be 26a4892f14ab077833059cad2ca465d34b003f1b .

**Comment by kennethreitz** [comment]
@javabrett want to send a fixing pr? :)

**Comment by javabrett** [comment]
@kennethreitz is there any quick way to ascertain which git commit httpbin.org is currently running?
