### ISSUE TITLE
Don't redirect to HTTPS

### ISSUE THREAD

**Issue by martmists** [requests/httpbin#489]
An application I'm currently testing requires requests to not be HTTPS as HTTPS is not supported, and it doesn't follow redirects.

**Comment by kennethreitz** [comment]
we don't

**Comment by martmists** [comment]
You do, http://httpbin.org/anything redirects to http**s**://httpbin.org/anything

**Comment by kennethreitz** [comment]
dns misconfiguration — give it time to propogate

**Comment by untitaker** [comment]
This recently regressed, on exactly the same endpoint @martmists originally reported it for. I opened #533

**Comment by cup** [comment]
https://github.com/postmanlabs/httpbin/issues/440

https://github.com/postmanlabs/httpbin/issues/489
https://github.com/postmanlabs/httpbin/issues/533
https://github.com/postmanlabs/httpbin/issues/536
https://github.com/postmanlabs/httpbin/issues/545
