### ISSUE TITLE
Connection header is incorrectly reported with value "close"

### ISSUE THREAD

**Issue by AdomasBekeras** [requests/httpbin#506]
httpbin.org is appending (or replacing if I send the Connection header with any value) the the Connection header on both HTTP and HTTPS responses. See attached screenshot from Fiddler.

![image](https://user-images.githubusercontent.com/20183755/44721012-43f7cc00-aad1-11e8-9de1-e54f308ffb17.png)

**Comment by sigmavirus24** [comment]
Load-balancers and other services that sit between you and the service are allowed by the spec to replace certain headers, including the Connection header.
